"""second migration.

Revision ID: 60e39fcb1abc
Revises: a18dbb5b5295
Create Date: 2023-08-01 00:41:41.077925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60e39fcb1abc'
down_revision = 'a18dbb5b5295'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=120), nullable=True))
        batch_op.drop_constraint('user_login_key', type_='unique')
        batch_op.drop_column('email')
        batch_op.drop_column('login')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('login', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('user_login_key', ['login'])
        batch_op.drop_column('username')

    # ### end Alembic commands ###
